/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthInput: typeof import('./src/components/ui/AuthInput.vue')['default']
    EditableForm: typeof import('./src/components/ui/EditableForm.vue')['default']
    Form: typeof import('./src/components/ui/Form.vue')['default']
    FormList: typeof import('./src/components/layout/FormList.vue')['default']
  }
}
